development:
  host: localhost
  database: golden_hope_development
  use_utc: true

test:
  host: localhost
  database: golden_hope_test

# set these environment variables on your prod server
production:
  host: localhost
  database: golden_hope_development
  use_utc: true
